In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Thuc_tap/data_final.csv')

In [ ]:
df.head()

,link,author,content,posted_time,Vị trí,crawl_time,Tài khoản,Nhóm ngành nghề,Lương,Thời gian làm,Hình thức nhận việc,Hình thức làm,Mô tả công việc,Nhãn,Lí do
0,https://www.facebook.com/share/p/1EMQhn3YE2/,Tổng Kho Kẹp Tóc,Tuyển nhân viên đóng gói hàng hóa nhẹ đơn giản...,NaN,Đóng gói hàng hóa,2025-06-05 20:03:46,Không,Lao động phổ thông,30000,9,Zalo,Part Time,Có,Lừa đảo,Việc nhẹ lương cao. Tài khoản này có tuyển nhi...
1,https://www.facebook.com/share/p/1CDaMEedqy/,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,NaN,Phụ bếp,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,32500,11,Zalo,Full time,Không,Thật,NaN
2,https://www.facebook.com/share/p/1CDaMEedqy/,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,NaN,Phục vụ,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,29000,11,Zalo,Full time,Không,Thật,NaN
3,https://www.facebook.com/share/p/1CDaMEedqy/,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,NaN,Tạp vụ,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,26000,11,Zalo,Full time,Không,Thật,NaN
4,https://www.facebook.com/share/p/1CDaMEedqy/,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,NaN,Order,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,29000,11,Zalo,Full time,Không,Thật,NaN

In [ ]:
df.shape

(6857, 15)

In [ ]:
df['Nhãn'].value_counts()
# Dữ liệu chêch lệch với gốc là do có nhiều dòng dữ liệu tuyển nhiều vị trí, và đã được tách ra thành các bản ghi

Nhãn
Thật       312
Lừa đảo    268
Unknow       6
Name: count, dtype: int64

# Lấy dữ liệu cho báo cáo

In [ ]:
df_temp = df[(df['Nhãn'] == 'Lừa đảo') | (df['Nhãn'] == 'Thật')]

In [ ]:
df_temp.shape

(580, 15)

In [ ]:
df_temp.reset_index(drop=True, inplace=True)

In [ ]:
df_temp.drop(['link','posted_time','Lí do'], axis=1, inplace=True)

/tmp/ipython-input-10-2913024822.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp.drop(['link','posted_time','Lí do'], axis=1, inplace=True)

In [ ]:
df_temp.isnull().sum()

author                   0
content                  0
Vị trí                   1
crawl_time               0
Tài khoản                0
Nhóm ngành nghề          0
Lương                  109
Thời gian làm          291
Hình thức nhận việc      0
Hình thức làm            0
Mô tả công việc          0
Nhãn                     0
dtype: int64

# Lấy dữ liệu cần thiết

In [ ]:
df_temp = df[(df['Nhãn'] == 'Lừa đảo') | (df['Nhãn'] == 'Thật')]

In [ ]:
df_temp.shape

(580, 15)

In [ ]:
df_temp.reset_index(drop=True, inplace=True)

In [ ]:
df_temp.head()

,link,author,content,posted_time,Vị trí,crawl_time,Tài khoản,Nhóm ngành nghề,Lương,Thời gian làm,Hình thức nhận việc,Hình thức làm,Mô tả công việc,Nhãn,Lí do
0,https://www.facebook.com/share/p/1EMQhn3YE2/,Tổng Kho Kẹp Tóc,Tuyển nhân viên đóng gói hàng hóa nhẹ đơn giản...,NaN,Đóng gói hàng hóa,2025-06-05 20:03:46,Không,Lao động phổ thông,30000,9,Zalo,Part Time,Có,Lừa đảo,Việc nhẹ lương cao. Tài khoản này có tuyển nhi...
1,https://www.facebook.com/share/p/1CDaMEedqy/,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,NaN,Phụ bếp,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,32500,11,Zalo,Full time,Không,Thật,NaN
2,https://www.facebook.com/share/p/1CDaMEedqy/,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,NaN,Phục vụ,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,29000,11,Zalo,Full time,Không,Thật,NaN
3,https://www.facebook.com/share/p/1CDaMEedqy/,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,NaN,Tạp vụ,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,26000,11,Zalo,Full time,Không,Thật,NaN
4,https://www.facebook.com/share/p/1CDaMEedqy/,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,NaN,Order,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,29000,11,Zalo,Full time,Không,Thật,NaN

In [ ]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 580 entries, 0 to 579
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   link                 580 non-null    object
 1   author               580 non-null    object
 2   content              580 non-null    object
 3   posted_time          0 non-null      float64
 4   Vị trí               579 non-null    object
 5   crawl_time           580 non-null    object
 6   Tài khoản            580 non-null    object
 7   Nhóm ngành nghề      580 non-null    object
 8   Lương                471 non-null    object
 9   Thời gian làm        289 non-null    object
 10  Hình thức nhận việc  580 non-null    object
 11  Hình thức làm        580 non-null    object
 12  Mô tả công việc      580 non-null    object
 13  Nhãn                 580 non-null    object
 14  Lí do                222 non-null    object
dtypes: float64(1), object(14)
memory usage: 68.1+ KB

In [ ]:
# df_temp.to_excel('data.xlsx', index=False)

## Lấy dữ liệu cho phần 1 (do chưa biết đặt tên là gì)
Có những bài tuyển dụng tuyển nhiều vị trí với các mức lương khác nhau => giải pháp là tạo ra nhiều bản ghi của các dòng đó cho mỗi vị trí. Tuy nhiên làm như vậy thì dẫn đến có các dòng trùng lặp nhiều, có thể gây sai lệch khi phân tích (vì những dòng có nhiều vị trí lại xuất hiện nhiều lần, mà mỗi dòng lại tương ứng với 1 bài tuyển dụng, việc xuất hiện nhiều lần như vậy dễ bị coi là spam). Do vậy t nghĩ nên chia ra 2 phần để phân tích 1 cách trực quan hơn.

In [ ]:
df_temp['posted_time'].value_counts()
# Loại bỏ crawl_time do nó không mang ý nghĩa quang trọng

Series([], Name: count, dtype: int64)

In [ ]:
df_part1 = df_temp[['author','content', 'crawl_time', 'Tài khoản','Nhóm ngành nghề', 'Hình thức nhận việc', 'Hình thức làm', 'Mô tả công việc', 'Nhãn']]

In [ ]:
df_part1.head()

,author,content,crawl_time,Tài khoản,Nhóm ngành nghề,Hình thức nhận việc,Hình thức làm,Mô tả công việc,Nhãn
0,Tổng Kho Kẹp Tóc,Tuyển nhân viên đóng gói hàng hóa nhẹ đơn giản...,2025-06-05 20:03:46,Không,Lao động phổ thông,Zalo,Part Time,Có,Lừa đảo
1,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,Zalo,Full time,Không,Thật
2,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,Zalo,Full time,Không,Thật
3,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,Zalo,Full time,Không,Thật
4,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,Zalo,Full time,Không,Thật

In [ ]:
df_part1.shape

(580, 9)

### Loại bỏ dữ liệu trùng lặp
Có thể loại bỏ dựa vào crawl_time. Vì những bản ghi được tạo ra vẫn giữa nguyên crawl_time gốc. (Thực sự có những bài spam)

In [ ]:
df_part1.drop_duplicates(inplace=True)

<ipython-input-109-4006277885>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_part1.drop_duplicates(inplace=True)

In [ ]:
df_part1.reset_index(drop=True, inplace=True)

In [ ]:
df_part1.head()

,author,content,crawl_time,Tài khoản,Nhóm ngành nghề,Hình thức nhận việc,Hình thức làm,Mô tả công việc,Nhãn
0,Tổng Kho Kẹp Tóc,Tuyển nhân viên đóng gói hàng hóa nhẹ đơn giản...,2025-06-05 20:03:46,Không,Lao động phổ thông,Zalo,Part Time,Có,Lừa đảo
1,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,Zalo,Full time,Không,Thật
2,Luci Hoàng,"tuyển Part Time , Full Time 🔥\n🎶 LIVE NHÓM TIK...",2025-06-06 01:41:52,Không,Nội dung số,"Zalo, Facebook","Part Time, Full time",Không,Lừa đảo
3,Phạm Thị Linh,Cửa Hàng NHÀ SÁCH bên mình đang tuyển nhâ...,2025-06-11 15:17:21,Không,Bán hàng - kinh doanh,Facebook,"Part Time, Full time, Online",Không,Lừa đảo
4,Phạm Thị Linh,Shop Gấu Online Bên Mình Tuyển GẤP Nhân Viên T...,2025-06-11 15:22:55,Không,Bán hàng - kinh doanh,Facebook,"Full time, Part Time, Online",Không,Lừa đảo

In [ ]:
df_part1.shape

(458, 9)

In [ ]:
df_part1['Nhãn'].value_counts()

Nhãn
Thật       248
Lừa đảo    210
Name: count, dtype: int64

### Kiểm tra giá trị thiếu

In [ ]:
df_part1.isnull().sum()

author                 0
content                0
crawl_time             0
Tài khoản              0
Nhóm ngành nghề        0
Hình thức nhận việc    0
Hình thức làm          0
Mô tả công việc        0
Nhãn                   0
dtype: int64

### Mã hóa trường dữ liệu
Do bài đổi, không cần xây mô hình nữa nên t nghĩ kh cần mã hóa nữa cũng được. Nhưng vẫn cần mã hóa 2 cột hình thức làm và hình thức nhận việc. Có gì mọi người chỉnh sửa cho phù hợp nha.

In [ ]:
# Cột nhãn, 1 là Lừa đảo, 0 là thật
df_part1['Nhãn'] = df_part1['Nhãn'].map(lambda x: 0 if x == 'Thật' else 1)
df_part1['Nhãn'].value_counts()

<ipython-input-115-2698063898>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_part1['Nhãn'] = df_part1['Nhãn'].map(lambda x: 0 if x == 'Thật' else 1)

Nhãn
0    248
1    210
Name: count, dtype: int64

In [ ]:
# Cột tài khoản
df_part1['Tài khoản'] = df_part1['Tài khoản'].map(lambda x: 0 if x == 'Không' else 1)
df_part1['Tài khoản'].value_counts()

<ipython-input-116-3400876452>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_part1['Tài khoản'] = df_part1['Tài khoản'].map(lambda x: 0 if x == 'Không' else 1)

Tài khoản
1    288
0    170
Name: count, dtype: int64

In [ ]:
# Cột mô tả công việc
df_part1['Mô tả công việc'] = df_part1['Mô tả công việc'].map(lambda x: 0 if x == 'Không' else 1)
df_part1['Mô tả công việc'].value_counts()

<ipython-input-117-3422170610>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_part1['Mô tả công việc'] = df_part1['Mô tả công việc'].map(lambda x: 0 if x == 'Không' else 1)

Mô tả công việc
0    285
1    173
Name: count, dtype: int64

In [ ]:
df_part1['Nhóm ngành nghề'].value_counts().sort_index()

Nhóm ngành nghề
Bán hàng - kinh doanh                                   104
Bán hàng - kinh doanh, Dịch vụ lưu trú                    1
Digital Marketing / Quảng cáo                             7
Digital Marketing / Quảng cáo, Bán hàng - kinh doanh      1
Dịch vụ                                                  15
Dịch vụ (nhạy cảm)                                       17
Dịch vụ lưu trú                                          12
Dịch vụ ăn uống                                         134
Lao động phổ thông                                       56
Nội dung số                                              25
Tư vấn - chăm sóc khách hàng                             13
Unknow                                                   38
Văn phòng - hành chính                                   33
Văn phòng - hành chính, Nội dung số                       1
Y tế                                                      1
Name: count, dtype: int64

In [ ]:
# Dùng Label Encoding cho cột Nhóm ngành nghề bởi mỗi dòng chỉ thuộc về 1 nhóm ngành
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_part1['Nhóm ngành nghề'] = le.fit_transform(df_part1['Nhóm ngành nghề'])

df_part1['Nhóm ngành nghề'].value_counts().sort_index()

<ipython-input-119-3171044863>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_part1['Nhóm ngành nghề'] = le.fit_transform(df_part1['Nhóm ngành nghề'])

Nhóm ngành nghề
0     104
1       1
2       7
3       1
4      15
5      17
6      12
7     134
8      56
9      25
10     13
11     38
12     33
13      1
14      1
Name: count, dtype: int64

In [ ]:
# Dùng one-hot cho các cột hình thức nhận việc, hình thức làm
df_part1['Hình thức làm'] = df_part1['Hình thức làm'].str.lower().str.replace(' ','').str.strip()
df_part1['Hình thức làm'] = df_part1['Hình thức làm'].str.split(',')

df_part1['Hình thức nhận việc'] = df_part1['Hình thức nhận việc'].str.lower().str.replace(' ','').str.strip()
df_part1['Hình thức nhận việc'] = df_part1['Hình thức nhận việc'].str.split(',')

<ipython-input-120-1659550290>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_part1['Hình thức làm'] = df_part1['Hình thức làm'].str.lower().str.replace(' ','').str.strip()
<ipython-input-120-1659550290>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_part1['Hình thức nhận việc'] = df_part1['Hình thức nhận việc'].str.lower().str.replace(' ','').str.strip()
<ipython-input-120-1659550290>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_part1['Hình thức làm'] = df_part1['Hình thức làm'].str.split(',')
<ipython-input-120-1659550290>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_part1['Hình thức nhận việc'] = df_part1['Hình thức nhận việc'].str.split(',')

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

labels_column = df_part1['Hình thức nhận việc']

mlb = MultiLabelBinarizer()
encoded = mlb.fit_transform(labels_column)
df_encoded = pd.DataFrame(encoded, columns=mlb.classes_, index=df_part1.index)
df_encoded.columns = ['Hình thức nhận việc - ' + col for col in df_encoded.columns]
df_encoded

,Hình thức nhận việc - email,Hình thức nhận việc - facebook,Hình thức nhận việc - telegram,Hình thức nhận việc - zalo
0,0,0,0,1
1,0,0,0,1
2,0,1,0,1
3,0,1,0,0
4,0,1,0,0
...,...,...,...,...
453,0,1,0,0
454,0,0,0,1
455,0,1,0,1
456,0,0,0,1
457,0,0,0,1

In [ ]:
df_temp_encoded = pd.concat([df_part1.iloc[:,:-2], df_encoded], axis=1)
df_temp_encoded.head()

,author,content,crawl_time,Tài khoản,Nhóm ngành nghề,Hình thức nhận việc,Hình thức làm,Hình thức nhận việc - email,Hình thức nhận việc - facebook,Hình thức nhận việc - telegram,Hình thức nhận việc - zalo
0,Tổng Kho Kẹp Tóc,Tuyển nhân viên đóng gói hàng hóa nhẹ đơn giản...,2025-06-05 20:03:46,0,8,[zalo],[parttime],0,0,0,1
1,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,2025-06-13 00:39:04,1,7,[zalo],[fulltime],0,0,0,1
2,Luci Hoàng,"tuyển Part Time , Full Time 🔥\n🎶 LIVE NHÓM TIK...",2025-06-06 01:41:52,0,9,"[zalo, facebook]","[parttime, fulltime]",0,1,0,1
3,Phạm Thị Linh,Cửa Hàng NHÀ SÁCH bên mình đang tuyển nhâ...,2025-06-11 15:17:21,0,0,[facebook],"[parttime, fulltime, online]",0,1,0,0
4,Phạm Thị Linh,Shop Gấu Online Bên Mình Tuyển GẤP Nhân Viên T...,2025-06-11 15:22:55,0,0,[facebook],"[fulltime, parttime, online]",0,1,0,0

In [ ]:
labels_column = df_part1['Hình thức làm']

mlb = MultiLabelBinarizer()
encoded = mlb.fit_transform(labels_column)
df_encoded = pd.DataFrame(encoded, columns=mlb.classes_, index=df_part1.index)
df_encoded.columns = ['Hình thức làm - ' + col for col in df_encoded.columns]
df_encoded

,Hình thức làm - fulltime,Hình thức làm - online,Hình thức làm - parttime,Hình thức làm - unknow
0,0,0,1,0
1,1,0,0,0
2,1,0,1,0
3,1,1,1,0
4,1,1,1,0
...,...,...,...,...
453,1,1,1,0
454,1,0,1,0
455,1,0,0,0
456,1,0,0,0
457,0,0,0,1

In [ ]:
df_temp_encoded = pd.concat([df_temp_encoded, df_encoded], axis=1)
df_temp_encoded.head()

,author,content,crawl_time,Tài khoản,Nhóm ngành nghề,Hình thức nhận việc,Hình thức làm,Hình thức nhận việc - email,Hình thức nhận việc - facebook,Hình thức nhận việc - telegram,Hình thức nhận việc - zalo,Hình thức làm - fulltime,Hình thức làm - online,Hình thức làm - parttime,Hình thức làm - unknow
0,Tổng Kho Kẹp Tóc,Tuyển nhân viên đóng gói hàng hóa nhẹ đơn giản...,2025-06-05 20:03:46,0,8,[zalo],[parttime],0,0,0,1,0,0,1,0
1,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,2025-06-13 00:39:04,1,7,[zalo],[fulltime],0,0,0,1,1,0,0,0
2,Luci Hoàng,"tuyển Part Time , Full Time 🔥\n🎶 LIVE NHÓM TIK...",2025-06-06 01:41:52,0,9,"[zalo, facebook]","[parttime, fulltime]",0,1,0,1,1,0,1,0
3,Phạm Thị Linh,Cửa Hàng NHÀ SÁCH bên mình đang tuyển nhâ...,2025-06-11 15:17:21,0,0,[facebook],"[parttime, fulltime, online]",0,1,0,0,1,1,1,0
4,Phạm Thị Linh,Shop Gấu Online Bên Mình Tuyển GẤP Nhân Viên T...,2025-06-11 15:22:55,0,0,[facebook],"[fulltime, parttime, online]",0,1,0,0,1,1,1,0

In [ ]:
df_part1 = pd.concat([df_temp_encoded, df_part1.iloc[:,-2:]], axis=1)

In [ ]:
df_part1.drop(['Hình thức làm', 'Hình thức nhận việc'], axis=1, inplace=True)

In [ ]:
df_part1.head()

,author,content,crawl_time,Tài khoản,Nhóm ngành nghề,Hình thức nhận việc - email,Hình thức nhận việc - facebook,Hình thức nhận việc - telegram,Hình thức nhận việc - zalo,Hình thức làm - fulltime,Hình thức làm - online,Hình thức làm - parttime,Hình thức làm - unknow,Mô tả công việc,Nhãn
0,Tổng Kho Kẹp Tóc,Tuyển nhân viên đóng gói hàng hóa nhẹ đơn giản...,2025-06-05 20:03:46,0,8,0,0,0,1,0,0,1,0,1,1
1,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,2025-06-13 00:39:04,1,7,0,0,0,1,1,0,0,0,0,0
2,Luci Hoàng,"tuyển Part Time , Full Time 🔥\n🎶 LIVE NHÓM TIK...",2025-06-06 01:41:52,0,9,0,1,0,1,1,0,1,0,0,1
3,Phạm Thị Linh,Cửa Hàng NHÀ SÁCH bên mình đang tuyển nhâ...,2025-06-11 15:17:21,0,0,0,1,0,0,1,1,1,0,0,1
4,Phạm Thị Linh,Shop Gấu Online Bên Mình Tuyển GẤP Nhân Viên T...,2025-06-11 15:22:55,0,0,0,1,0,0,1,1,1,0,0,1

In [ ]:
df_part1.shape

(458, 15)

In [ ]:
df_part1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   author                          458 non-null    object
 1   content                         458 non-null    object
 2   crawl_time                      458 non-null    object
 3   Tài khoản                       458 non-null    int64
 4   Nhóm ngành nghề                 458 non-null    int64
 5   Hình thức nhận việc - email     458 non-null    int64
 6   Hình thức nhận việc - facebook  458 non-null    int64
 7   Hình thức nhận việc - telegram  458 non-null    int64
 8   Hình thức nhận việc - zalo      458 non-null    int64
 9   Hình thức làm - fulltime        458 non-null    int64
 10  Hình thức làm - online          458 non-null    int64
 11  Hình thức làm - parttime        458 non-null    int64
 12  Hình thức làm - unknow          458 non-null    int64
 13  Mô tả công việc                 458 non-null    int64
 14  Nhãn                            458 non-null    int64
dtypes: int64(12), object(3)
memory usage: 53.8+ KB

In [ ]:
# Xử lý phần time nữa

## Lấy dữ liệu cho phần 2
Phần này dùng để phân tích về lương và giờ làm. T nghĩ có thể bỏ cột vị trí, phân tích dựa trên nhóm ngành nghề, lương và giờ làm.
VD: nhóm ngành nghề này có bao nhiêu cái là lừa đảo. bao nhiêu cái là lừa đảo và không công khai lương, giờ làm. Bao nhiêu cái là thật nhưng không công khai lương và giờ làm.

* Lương tính theo giờ
* Thời gian làm tính theo ngày nha

In [ ]:
df_part2 = df_temp[['author', 'Vị trí', 'Nhóm ngành nghề', 'Lương', 'Thời gian làm', 'Hình thức làm', 'Nhãn']]
# Thêm các trường mà mọi người thấy là cần thiết nha

In [ ]:
df_part2.head()

,author,Vị trí,Nhóm ngành nghề,Lương,Thời gian làm,Hình thức làm,Nhãn
0,Tổng Kho Kẹp Tóc,Đóng gói hàng hóa,Lao động phổ thông,30000,9,Part Time,Lừa đảo
1,Nguyễn Kim Anh,Phụ bếp,Dịch vụ ăn uống,32500,11,Full time,Thật
2,Nguyễn Kim Anh,Phục vụ,Dịch vụ ăn uống,29000,11,Full time,Thật
3,Nguyễn Kim Anh,Tạp vụ,Dịch vụ ăn uống,26000,11,Full time,Thật
4,Nguyễn Kim Anh,Order,Dịch vụ ăn uống,29000,11,Full time,Thật

### Mã hóa

In [ ]:
#Mã hóa cột hình thức làm
df_part2['Hình thức làm'] = df_part2['Hình thức làm'].str.lower().str.replace(' ','').str.strip()
df_part2['Hình thức làm'] = df_part2['Hình thức làm'].str.split(',')

<ipython-input-161-2896727796>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_part2['Hình thức làm'] = df_part2['Hình thức làm'].str.lower().str.replace(' ','').str.strip()
<ipython-input-161-2896727796>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_part2['Hình thức làm'] = df_part2['Hình thức làm'].str.split(',')

In [ ]:
labels_column = df_part2['Hình thức làm']

mlb = MultiLabelBinarizer()
encoded = mlb.fit_transform(labels_column)
df_encoded = pd.DataFrame(encoded, columns=mlb.classes_, index=df_part2.index)
df_encoded.columns = ['Hình thức làm - ' + col for col in df_encoded.columns]
df_encoded

,Hình thức làm - fulltime,Hình thức làm - online,Hình thức làm - parttime,Hình thức làm - unknow
0,0,0,1,0
1,1,0,0,0
2,1,0,0,0
3,1,0,0,0
4,1,0,0,0
...,...,...,...,...
575,1,1,1,0
576,1,0,1,0
577,1,0,0,0
578,1,0,0,0
579,0,0,0,1

In [ ]:
df_part2_temp = pd.concat([df_part2.iloc[:,:-2], df_encoded], axis=1)

In [ ]:
df_part2 = pd.concat([df_part2_temp, df_part2.iloc[:,-2:]], axis=1)

In [ ]:
df_part2.drop(['Hình thức làm'], axis=1, inplace=True)

In [ ]:
df_part2.head()

,author,Vị trí,Nhóm ngành nghề,Lương,Thời gian làm,Hình thức làm - fulltime,Hình thức làm - online,Hình thức làm - parttime,Hình thức làm - unknow,Nhãn
0,Tổng Kho Kẹp Tóc,Đóng gói hàng hóa,Lao động phổ thông,30000,9,0,0,1,0,Lừa đảo
1,Nguyễn Kim Anh,Phụ bếp,Dịch vụ ăn uống,32500,11,1,0,0,0,Thật
2,Nguyễn Kim Anh,Phục vụ,Dịch vụ ăn uống,29000,11,1,0,0,0,Thật
3,Nguyễn Kim Anh,Tạp vụ,Dịch vụ ăn uống,26000,11,1,0,0,0,Thật
4,Nguyễn Kim Anh,Order,Dịch vụ ăn uống,29000,11,1,0,0,0,Thật

### Kiểm tra giá trị thiếu
Lương và thời gian làm vẫn thiếu rất nhiều (Do có nhiều nhà tuyển dụng không công khai) => đề xuất tách ra phân tích riêng phần thiếu và không thiếu.

In [ ]:
df_part2.isnull().sum()

author                        0
Vị trí                        1
Nhóm ngành nghề               0
Lương                       109
Thời gian làm               291
Hình thức làm - fulltime      0
Hình thức làm - online        0
Hình thức làm - parttime      0
Hình thức làm - unknow        0
Nhãn                          0
dtype: int64

In [ ]:
df_luong_null = df_part2[df_part2['Lương'].isnull()]
df_luong_null.head()

,author,Vị trí,Nhóm ngành nghề,Lương,Thời gian làm,Hình thức làm - fulltime,Hình thức làm - online,Hình thức làm - parttime,Hình thức làm - unknow,Nhãn
48,HaoChi - Dimsum Taipei Hà Nội,NaN,Dịch vụ ăn uống,NaN,NaN,1,0,0,0,Thật
49,Nguyễn Thị Hạnh,Nhân viên đóng gói,Lao động phổ thông,NaN,"13,5",0,1,0,0,Lừa đảo
58,Phuc Long Tea & Coffee Careers,Thực tập sinh,Dịch vụ ăn uống,NaN,NaN,1,0,0,0,Thật
69,VNPT - Tuyển Dụng,Kế toán,Văn phòng - hành chính,NaN,NaN,1,0,0,0,Lừa đảo
74,Nguyễn Điệp,Trưởng nhóm HSE,Unknow,NaN,NaN,0,0,0,1,Lừa đảo

In [ ]:
df_luong_not_null = df_part2[df_part2['Lương'].notnull()]
df_luong_not_null.head()

,author,Vị trí,Nhóm ngành nghề,Lương,Thời gian làm,Hình thức làm - fulltime,Hình thức làm - online,Hình thức làm - parttime,Hình thức làm - unknow,Nhãn
0,Tổng Kho Kẹp Tóc,Đóng gói hàng hóa,Lao động phổ thông,30000,9,0,0,1,0,Lừa đảo
1,Nguyễn Kim Anh,Phụ bếp,Dịch vụ ăn uống,32500,11,1,0,0,0,Thật
2,Nguyễn Kim Anh,Phục vụ,Dịch vụ ăn uống,29000,11,1,0,0,0,Thật
3,Nguyễn Kim Anh,Tạp vụ,Dịch vụ ăn uống,26000,11,1,0,0,0,Thật
4,Nguyễn Kim Anh,Order,Dịch vụ ăn uống,29000,11,1,0,0,0,Thật

In [ ]:
df_tglam_null = df_part2[df_part2['Thời gian làm'].isnull()]
df_tglam_null.head()

,author,Vị trí,Nhóm ngành nghề,Lương,Thời gian làm,Hình thức làm - fulltime,Hình thức làm - online,Hình thức làm - parttime,Hình thức làm - unknow,Nhãn
20,Bích Hạnh,Soạn thảo văn bản,Nội dung số,35000,NaN,0,1,1,0,Lừa đảo
21,Nguyen Anh Tuan,Soạn thảo văn bản,Nội dung số,37500,NaN,1,1,1,0,Lừa đảo
25,Phạm Thứ,livestream,Nội dung số,50000,NaN,0,0,0,1,Lừa đảo
36,Nguyễn Thương,Công nhân gia công,Lao động phổ thông,37500,NaN,0,0,1,0,Lừa đảo
42,Bạch Diệp,Vận hành,Dịch vụ,80000,NaN,0,0,0,1,Lừa đảo

In [ ]:
df_tglam_notnull = df_part2[df_part2['Thời gian làm'].notnull()]
df_tglam_notnull.head()

,author,Vị trí,Nhóm ngành nghề,Lương,Thời gian làm,Hình thức làm - fulltime,Hình thức làm - online,Hình thức làm - parttime,Hình thức làm - unknow,Nhãn
0,Tổng Kho Kẹp Tóc,Đóng gói hàng hóa,Lao động phổ thông,30000,9,0,0,1,0,Lừa đảo
1,Nguyễn Kim Anh,Phụ bếp,Dịch vụ ăn uống,32500,11,1,0,0,0,Thật
2,Nguyễn Kim Anh,Phục vụ,Dịch vụ ăn uống,29000,11,1,0,0,0,Thật
3,Nguyễn Kim Anh,Tạp vụ,Dịch vụ ăn uống,26000,11,1,0,0,0,Thật
4,Nguyễn Kim Anh,Order,Dịch vụ ăn uống,29000,11,1,0,0,0,Thật