In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Thuc_tap/data_ld.csv')

In [ ]:
df.head()

,link,author,content,posted_time,crawl_time,Tài khoản,Nhóm ngành nghề,Lương,Thời gian làm,Hình thức nhận việc,Hình thức làm,Mô tả công việc,Nhãn,Lí do
0,https://www.facebook.com/share/p/1EMQhn3YE2/,Tổng Kho Kẹp Tóc,Tuyển nhân viên đóng gói hàng hóa nhẹ đơn giản...,NaN,2025-06-05 20:03:46,Không,Lao động phổ thông,NaN,NaN,Zalo,Part Time,Có,Lừa đảo,Việc nhẹ lương cao. Tài khoản này có tuyển nhi...
1,https://www.facebook.com/share/p/1CDaMEedqy/,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,NaN,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,NaN,NaN,Zalo,Full time,Không,Thật,NaN
2,https://www.facebook.com/groups/14059423233826...,Luci Hoàng,"tuyển Part Time , Full Time 🔥\n🎶 LIVE NHÓM TIK...",NaN,2025-06-06 01:41:52,Không,Nội dung số,10000000-40000000,"10h-16h, 18h-24h, 8h45-17h45","Zalo, Facebook","Part Time, Full time",Không,Lừa đảo,Việc nhẹ lương cao
3,https://www.facebook.com/share/p/12M2zEv7z6n/,Phạm Thị Linh,Cửa Hàng NHÀ SÁCH bên mình đang tuyển nhâ...,NaN,2025-06-11 15:17:21,Không,Bán hàng - kinh doanh,NaN,NaN,Facebook,"Part Time, Full time",Không,Lừa đảo,"Tài khoản giả mạo, đăng nhiều tin tuyển dụng c..."
4,https://www.facebook.com/share/p/16fjX3zGT5/,Phạm Thị Linh,Shop Gấu Online Bên Mình Tuyển GẤP Nhân Viên T...,NaN,2025-06-11 15:22:55,Không,Bán hàng - kinh doanh,NaN,NaN,Facebook,"Full time, Part Time",Không,Lừa đảo,"Tài khoản giả mạo, đăng nhiều tin tuyển dụng c..."

In [ ]:
df.shape

(6739, 14)

In [ ]:
df['Nhãn'].value_counts()

Nhãn
Thật       250
Lừa đảo    212
Unknow       6
Name: count, dtype: int64

## Lấy dữ liệu cần thiết

In [ ]:
df_temp = df[(df['Nhãn'] == 'Lừa đảo') | (df['Nhãn'] == 'Thật')]

In [ ]:
df_temp.shape

(462, 14)

In [ ]:
df_temp.reset_index(drop=True, inplace=True)

In [ ]:
df_temp.head()

,link,author,content,posted_time,crawl_time,Tài khoản,Nhóm ngành nghề,Lương,Thời gian làm,Hình thức nhận việc,Hình thức làm,Mô tả công việc,Nhãn,Lí do
0,https://www.facebook.com/share/p/1EMQhn3YE2/,Tổng Kho Kẹp Tóc,Tuyển nhân viên đóng gói hàng hóa nhẹ đơn giản...,NaN,2025-06-05 20:03:46,Không,Lao động phổ thông,NaN,NaN,Zalo,Part Time,Có,Lừa đảo,Việc nhẹ lương cao. Tài khoản này có tuyển nhi...
1,https://www.facebook.com/share/p/1CDaMEedqy/,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,NaN,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,NaN,NaN,Zalo,Full time,Không,Thật,NaN
2,https://www.facebook.com/groups/14059423233826...,Luci Hoàng,"tuyển Part Time , Full Time 🔥\n🎶 LIVE NHÓM TIK...",NaN,2025-06-06 01:41:52,Không,Nội dung số,10000000-40000000,"10h-16h, 18h-24h, 8h45-17h45","Zalo, Facebook","Part Time, Full time",Không,Lừa đảo,Việc nhẹ lương cao
3,https://www.facebook.com/share/p/12M2zEv7z6n/,Phạm Thị Linh,Cửa Hàng NHÀ SÁCH bên mình đang tuyển nhâ...,NaN,2025-06-11 15:17:21,Không,Bán hàng - kinh doanh,NaN,NaN,Facebook,"Part Time, Full time",Không,Lừa đảo,"Tài khoản giả mạo, đăng nhiều tin tuyển dụng c..."
4,https://www.facebook.com/share/p/16fjX3zGT5/,Phạm Thị Linh,Shop Gấu Online Bên Mình Tuyển GẤP Nhân Viên T...,NaN,2025-06-11 15:22:55,Không,Bán hàng - kinh doanh,NaN,NaN,Facebook,"Full time, Part Time",Không,Lừa đảo,"Tài khoản giả mạo, đăng nhiều tin tuyển dụng c..."

In [ ]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 462 entries, 0 to 461
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   link                 462 non-null    object
 1   author               462 non-null    object
 2   content              462 non-null    object
 3   posted_time          0 non-null      float64
 4   crawl_time           462 non-null    object
 5   Tài khoản            462 non-null    object
 6   Nhóm ngành nghề      462 non-null    object
 7   Lương                271 non-null    object
 8   Thời gian làm        152 non-null    object
 9   Hình thức nhận việc  462 non-null    object
 10  Hình thức làm        462 non-null    object
 11  Mô tả công việc      462 non-null    object
 12  Nhãn                 462 non-null    object
 13  Lí do                170 non-null    object
dtypes: float64(1), object(13)
memory usage: 50.7+ KB

In [ ]:
# df_temp.to_excel('data.xlsx', index=False)

## Loại bỏ cột thừa

In [ ]:
df_temp['posted_time'].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
df_temp.drop(['link','posted_time', 'Thời gian làm','Lí do'], axis=1, inplace=True)

<ipython-input-13-1499177660>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp.drop(['link','posted_time', 'Thời gian làm','Lí do'], axis=1, inplace=True)

In [ ]:
df_temp.head()

,author,content,crawl_time,Tài khoản,Nhóm ngành nghề,Lương,Hình thức nhận việc,Hình thức làm,Mô tả công việc,Nhãn
0,Tổng Kho Kẹp Tóc,Tuyển nhân viên đóng gói hàng hóa nhẹ đơn giản...,2025-06-05 20:03:46,Không,Lao động phổ thông,NaN,Zalo,Part Time,Có,Lừa đảo
1,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,2025-06-13 00:39:04,Có,Dịch vụ ăn uống,NaN,Zalo,Full time,Không,Thật
2,Luci Hoàng,"tuyển Part Time , Full Time 🔥\n🎶 LIVE NHÓM TIK...",2025-06-06 01:41:52,Không,Nội dung số,10000000-40000000,"Zalo, Facebook","Part Time, Full time",Không,Lừa đảo
3,Phạm Thị Linh,Cửa Hàng NHÀ SÁCH bên mình đang tuyển nhâ...,2025-06-11 15:17:21,Không,Bán hàng - kinh doanh,NaN,Facebook,"Part Time, Full time",Không,Lừa đảo
4,Phạm Thị Linh,Shop Gấu Online Bên Mình Tuyển GẤP Nhân Viên T...,2025-06-11 15:22:55,Không,Bán hàng - kinh doanh,NaN,Facebook,"Full time, Part Time",Không,Lừa đảo

In [ ]:
df_temp.shape

(462, 10)

## Kiểm tra giá trị thiếu

In [ ]:
df_temp.isnull().sum()

author                   0
content                  0
crawl_time               0
Tài khoản                0
Nhóm ngành nghề          0
Lương                  191
Hình thức nhận việc      0
Hình thức làm            0
Mô tả công việc          0
Nhãn                     0
dtype: int64

In [ ]:
df_temp.drop('Lương', axis=1, inplace=True)

<ipython-input-17-1519440968>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp.drop('Lương', axis=1, inplace=True)

In [ ]:
df_temp.isnull().sum()

author                 0
content                0
crawl_time             0
Tài khoản              0
Nhóm ngành nghề        0
Hình thức nhận việc    0
Hình thức làm          0
Mô tả công việc        0
Nhãn                   0
dtype: int64

## Mã hóa trường dữ liệu

In [ ]:
# Cột nhãn, 1 là Lừa đảo, 0 là thật
df_temp['Nhãn'] = df_temp['Nhãn'].map(lambda x: 0 if x == 'Thật' else 1)
df_temp['Nhãn'].value_counts()

<ipython-input-19-2642059780>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp['Nhãn'] = df_temp['Nhãn'].map(lambda x: 0 if x == 'Thật' else 1)

Nhãn
0    250
1    212
Name: count, dtype: int64

In [ ]:
# Cột tài khoản
df_temp['Tài khoản'] = df_temp['Tài khoản'].map(lambda x: 0 if x == 'Không' else 1)
df_temp['Tài khoản'].value_counts()

<ipython-input-20-2113762968>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp['Tài khoản'] = df_temp['Tài khoản'].map(lambda x: 0 if x == 'Không' else 1)

Tài khoản
1    290
0    172
Name: count, dtype: int64

In [ ]:
# Cột mô tả công việc
df_temp['Mô tả công việc'] = df_temp['Mô tả công việc'].map(lambda x: 0 if x == 'Không' else 1)
df_temp['Mô tả công việc'].value_counts()

<ipython-input-21-3090278974>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp['Mô tả công việc'] = df_temp['Mô tả công việc'].map(lambda x: 0 if x == 'Không' else 1)

Mô tả công việc
0    287
1    175
Name: count, dtype: int64

In [ ]:
df_temp['Nhóm ngành nghề'].value_counts().sort_index()

Nhóm ngành nghề
Bán hàng - kinh doanh                                   103
Bán hàng - kinh doanh, Dịch vụ lưu trú                    1
Digital Marketing / Quảng cáo                             8
Digital Marketing / Quảng cáo, Bán hàng - kinh doanh      1
Dịch vụ                                                  15
Dịch vụ (nhạy cảm)                                       18
Dịch vụ lưu trú                                          14
Dịch vụ ăn uống                                         131
Dịch vụ ăn uống, Bán hàng - kinh doanh                    1
Lao động phổ thông                                       56
Nội dung số                                              28
Tư vấn - chăm sóc khách hàng                             11
Unknow                                                   40
Văn phòng - hành chính                                   32
Văn phòng - hành chính, Nội dung số                       2
Y tế                                                      1
Name: count, dtype: int64

In [ ]:
# Dùng Label Encoding cho cột Nhóm ngành nghề bởi mỗi dòng chỉ thuộc về 1 nhóm ngành
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_temp['Nhóm ngành nghề'] = le.fit_transform(df_temp['Nhóm ngành nghề'])

df_temp['Nhóm ngành nghề'].value_counts().sort_index()

<ipython-input-23-3510055708>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp['Nhóm ngành nghề'] = le.fit_transform(df_temp['Nhóm ngành nghề'])

Nhóm ngành nghề
0     103
1       1
2       8
3       1
4      15
5      18
6      14
7     131
8       1
9      56
10     28
11     11
12     40
13     32
14      2
15      1
Name: count, dtype: int64

In [ ]:
# Dùng one-hot cho các cột hình thức nhận việc, hình thức làm
df_temp['Hình thức làm'] = df_temp['Hình thức làm'].str.lower().str.replace(' ','').str.strip()
df_temp['Hình thức nhận việc'] = df_temp['Hình thức nhận việc'].str.lower().str.replace(' ','').str.strip()

df_temp['Hình thức làm'] = df_temp['Hình thức làm'].str.split(',')
df_temp['Hình thức nhận việc'] = df_temp['Hình thức nhận việc'].str.split(',')

<ipython-input-24-2861695396>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp['Hình thức làm'] = df_temp['Hình thức làm'].str.lower().str.replace(' ','').str.strip()
<ipython-input-24-2861695396>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp['Hình thức nhận việc'] = df_temp['Hình thức nhận việc'].str.lower().str.replace(' ','').str.strip()
<ipython-input-24-2861695396>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp['Hình thức làm'] = df_temp['Hình thức làm'].str.split(',')
<ipython-input-24-2861695396>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp['Hình thức nhận việc'] = df_temp['Hình thức nhận việc'].str.split(',')

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

labels_column = df_temp['Hình thức nhận việc']

mlb = MultiLabelBinarizer()
encoded = mlb.fit_transform(labels_column)
df_encoded = pd.DataFrame(encoded, columns=mlb.classes_, index=df_temp.index)
df_encoded.columns = ['Hình thức nhận việc - ' + col for col in df_encoded.columns]
df_encoded

,Hình thức nhận việc - email,Hình thức nhận việc - facebook,Hình thức nhận việc - telegram,Hình thức nhận việc - zalo
0,0,0,0,1
1,0,0,0,1
2,0,1,0,1
3,0,1,0,0
4,0,1,0,0
...,...,...,...,...
457,0,1,0,0
458,0,0,0,1
459,0,1,0,1
460,0,0,0,1
461,0,0,0,1

In [ ]:
df_temp_encoded = pd.concat([df_temp.iloc[:,:-2], df_encoded], axis=1)
df_temp_encoded.head()

,author,content,crawl_time,Tài khoản,Nhóm ngành nghề,Hình thức nhận việc,Hình thức làm,Hình thức nhận việc - email,Hình thức nhận việc - facebook,Hình thức nhận việc - telegram,Hình thức nhận việc - zalo
0,Tổng Kho Kẹp Tóc,Tuyển nhân viên đóng gói hàng hóa nhẹ đơn giản...,2025-06-05 20:03:46,0,9,[zalo],[parttime],0,0,0,1
1,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,2025-06-13 00:39:04,1,7,[zalo],[fulltime],0,0,0,1
2,Luci Hoàng,"tuyển Part Time , Full Time 🔥\n🎶 LIVE NHÓM TIK...",2025-06-06 01:41:52,0,10,"[zalo, facebook]","[parttime, fulltime]",0,1,0,1
3,Phạm Thị Linh,Cửa Hàng NHÀ SÁCH bên mình đang tuyển nhâ...,2025-06-11 15:17:21,0,0,[facebook],"[parttime, fulltime]",0,1,0,0
4,Phạm Thị Linh,Shop Gấu Online Bên Mình Tuyển GẤP Nhân Viên T...,2025-06-11 15:22:55,0,0,[facebook],"[fulltime, parttime]",0,1,0,0

In [ ]:
labels_column = df_temp['Hình thức làm']

mlb = MultiLabelBinarizer()
encoded = mlb.fit_transform(labels_column)
df_encoded = pd.DataFrame(encoded, columns=mlb.classes_, index=df_temp.index)
df_encoded.columns = ['Hình thức làm - ' + col for col in df_encoded.columns]
df_encoded

,Hình thức làm - fulltime,Hình thức làm - online,Hình thức làm - parttime,Hình thức làm - unknow
0,0,0,1,0
1,1,0,0,0
2,1,0,1,0
3,1,0,1,0
4,1,0,1,0
...,...,...,...,...
457,1,1,1,0
458,1,0,1,0
459,1,0,0,0
460,1,0,0,0
461,0,0,0,1

In [ ]:
df_temp_encoded = pd.concat([df_temp_encoded, df_encoded], axis=1)
df_temp_encoded.head()

,author,content,crawl_time,Tài khoản,Nhóm ngành nghề,Hình thức nhận việc,Hình thức làm,Hình thức nhận việc - email,Hình thức nhận việc - facebook,Hình thức nhận việc - telegram,Hình thức nhận việc - zalo,Hình thức làm - fulltime,Hình thức làm - online,Hình thức làm - parttime,Hình thức làm - unknow
0,Tổng Kho Kẹp Tóc,Tuyển nhân viên đóng gói hàng hóa nhẹ đơn giản...,2025-06-05 20:03:46,0,9,[zalo],[parttime],0,0,0,1,0,0,1,0
1,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,2025-06-13 00:39:04,1,7,[zalo],[fulltime],0,0,0,1,1,0,0,0
2,Luci Hoàng,"tuyển Part Time , Full Time 🔥\n🎶 LIVE NHÓM TIK...",2025-06-06 01:41:52,0,10,"[zalo, facebook]","[parttime, fulltime]",0,1,0,1,1,0,1,0
3,Phạm Thị Linh,Cửa Hàng NHÀ SÁCH bên mình đang tuyển nhâ...,2025-06-11 15:17:21,0,0,[facebook],"[parttime, fulltime]",0,1,0,0,1,0,1,0
4,Phạm Thị Linh,Shop Gấu Online Bên Mình Tuyển GẤP Nhân Viên T...,2025-06-11 15:22:55,0,0,[facebook],"[fulltime, parttime]",0,1,0,0,1,0,1,0

In [ ]:
df_temp = pd.concat([df_temp_encoded, df_temp.iloc[:,-2:]], axis=1)

In [ ]:
df_temp.drop(['Hình thức làm', 'Hình thức nhận việc'], axis=1, inplace=True)

In [ ]:
df_temp.head()

,author,content,crawl_time,Tài khoản,Nhóm ngành nghề,Hình thức nhận việc - email,Hình thức nhận việc - facebook,Hình thức nhận việc - telegram,Hình thức nhận việc - zalo,Hình thức làm - fulltime,Hình thức làm - online,Hình thức làm - parttime,Hình thức làm - unknow,Mô tả công việc,Nhãn
0,Tổng Kho Kẹp Tóc,Tuyển nhân viên đóng gói hàng hóa nhẹ đơn giản...,2025-06-05 20:03:46,0,9,0,0,0,1,0,0,1,0,1,1
1,Nguyễn Kim Anh,💥Nhà Hàng LẨU NƯỚNG cần tuyển nhân viên đi là...,2025-06-13 00:39:04,1,7,0,0,0,1,1,0,0,0,0,0
2,Luci Hoàng,"tuyển Part Time , Full Time 🔥\n🎶 LIVE NHÓM TIK...",2025-06-06 01:41:52,0,10,0,1,0,1,1,0,1,0,0,1
3,Phạm Thị Linh,Cửa Hàng NHÀ SÁCH bên mình đang tuyển nhâ...,2025-06-11 15:17:21,0,0,0,1,0,0,1,0,1,0,0,1
4,Phạm Thị Linh,Shop Gấu Online Bên Mình Tuyển GẤP Nhân Viên T...,2025-06-11 15:22:55,0,0,0,1,0,0,1,0,1,0,0,1

In [ ]:
df_temp.shape

(462, 15)

In [ ]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 462 entries, 0 to 461
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   author                          462 non-null    object
 1   content                         462 non-null    object
 2   crawl_time                      462 non-null    object
 3   Tài khoản                       462 non-null    int64
 4   Nhóm ngành nghề                 462 non-null    int64
 5   Hình thức nhận việc - email     462 non-null    int64
 6   Hình thức nhận việc - facebook  462 non-null    int64
 7   Hình thức nhận việc - telegram  462 non-null    int64
 8   Hình thức nhận việc - zalo      462 non-null    int64
 9   Hình thức làm - fulltime        462 non-null    int64
 10  Hình thức làm - online          462 non-null    int64
 11  Hình thức làm - parttime        462 non-null    int64
 12  Hình thức làm - unknow          462 non-null    int64
 13  Mô tả công việc                 462 non-null    int64
 14  Nhãn                            462 non-null    int64
dtypes: int64(12), object(3)
memory usage: 54.3+ KB

In [ ]:
# Xử lý phần time nữa